version: 1
policy:
  pullRequests: collaborators
tasks:
  $if: tasks_for == "github-push"
  then:
    $if: event.ref == "refs/heads/master"
    then:
      $flattenDeep:
        $map: [{name: firefox, channel: nightly}]
        each(browser):
          $map:
            - [testharness, 11, 15, 0]
            - [testharness, 11, 15, 1]
            - [testharness, 11, 15, 2]
            - [testharness, 11, 15, 3]
            - [testharness, 11, 15, 4]
            - [testharness, 11, 15, 5]
            - [testharness, 11, 15, 6]
            - [testharness, 11, 15, 7]
            - [testharness, 11, 15, 8]
            - [testharness, 11, 15, 9]
            - [testharness, 11, 15, 10]
            - [testharness, 11, 15, 11]
            - [testharness, 11, 15, 12]
            - [testharness, 11, 15, 13]
            - [testharness, 11, 15, 14]
            - [testharness, 11, 15, 15]
            - [testharness, 11, 15, 16]
            - [testharness, 11, 15, 17]
            - [testharness, 11, 15, 18]
            - [testharness, 11, 15, 19]
          each(chunk): 
            taskId: {$eval: 'as_slugid(str(chunk[3]))'}
            taskGroupId: {$eval: 'as_slugid("task group")'}
            created: {$fromNow: ''}
            deadline: {$fromNow: '24 hours'}
            provisionerId: aws-provisioner-v1
            workerType: github-worker
            metadata:
              name: wpt-${browser.name}-${browser.channel}-${chunk[0]}-${chunk[1]}
              description: A subset "${chunk[0]}" tests
              owner: ${event.pusher.email}
              source: ${event.repository.url}
            payload:
              image: gsnedders/web-platform-tests:0.13
              maxRunTime: 7200
              artifacts:
                public/results:
                  path: /home/test/artifacts
                  type: directory
              command:
                - /bin/bash
                - --login
                - -c
                - "~/start.sh ${event.repository.url} ${event.ref[11:]} ${event.after} ${browser.name}-${browser.channel} &&
                  cd ~/web-platform-tests &&
                  ./tools/ci/ci_taskcluster.sh ${browser.name} ${chunk[0]} ${chunk[1]} ${chunk[2]}"
    else: []
  else: []
