dist: trusty
sudo: required
language: python
branches:
  only:
    - master
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  # This needs be sourced as it sets various env vars
  - . ./tools/ci/before_install.sh
install:
  - ./tools/ci/install.sh
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: JOB=tools_unittest TOXENV=py27 HYPOTHESIS_PROFILE=ci SCRIPT=tools/ci/ci_tools_unittest.sh
  exclude:
    - env:  # exclude empty env from the top-level above
  allow_failures:
    - env: JOB=build_css SCRIPT=css/build-css-testsuites.sh
script:
  - ./tools/ci/run.sh
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
