dist: trusty
sudo: required
language: python
branches:
  only:
    - master
script:
  - git log --oneline --graph | head -n 20
  - git rev-parse HEAD
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
